#!/usr/bin/env python3
"""Emit the linker's export control from scripts/symbols.txt: build/zlib.map, an ELF version
script saying "publish exactly these names and nothing else".

That second half is the load-bearing one: a Swift library exports a great deal besides its own
API — type metadata, protocol witnesses, module descriptors — and a client that resolved one of
those would bind to something that is not a contract and will not survive a recompile.

The script additionally reproduces the reference's *symbol versions*. A client compiled
against zlib 1.2.9 records a dependency on adler32_z@ZLIB_1.2.9, and the dynamic linker
resolves it by name and node together, so a library offering an unversioned adler32_z does not
satisfy it. The 41 symbols that predate versioning are left out of every node, which leaves them
global and unversioned — how they appear in the reference, and what lets a binary linked against
this library still run against the real one.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMBOLS = ROOT / "scripts" / "symbols.txt"

UNVERSIONED = "(unversioned)"


def load():
    groups, current = {}, None

    for line in SYMBOLS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1]
            groups.setdefault(current, [])
            continue
        if current is None:
            raise SystemExit(f"gen_symbols: symbol {line!r} before any version heading")
        groups[current].append(line)

    return groups


def version_key(name):
    if name == UNVERSIONED:
        return (0,)
    return (1,) + tuple(int(part) for part in name.removeprefix("ZLIB_").split("."))


# Everything a Swift library exports besides its own API. Hidden by pattern rather than by
# `local: *`, because `local: *` is only available in an anonymous version node and GNU ld
# refuses to combine an anonymous node with named ones — and the named nodes are not optional,
# since they are how a client's `adler32_z@ZLIB_1.2.9` resolves.
#
# scripts/check_exports.sh is what makes this safe: it asserts the built library exports exactly
# the reference's set, so a pattern that misses something fails the build rather than shipping.
INTERNAL_PATTERNS = [
    # Unquoted deliberately: a version script treats a quoted string as a literal symbol
    # name and only an unquoted one as a glob, so "$s*" would match nothing at all.
    "$s*",              # Swift mangled names: types, metadata, witnesses, descriptors
    "_$s*",
    "swift_*",          # the Swift runtime, when statically linked in
    "_swift*",
    "__swift*",
    "__start_swift*",   # section bounds the linker synthesises for Swift metadata
    "__stop_swift*",
    "swiftzlib_*",      # this library's own C internals
]


def write_version_script(groups, out):
    lines = [
        "/* Generated by scripts/gen_symbols.py. Do not edit.",
        " *",
        " * Named nodes only, exactly as the reference's own map is written. The symbols that",
        " * predate zlib's versioning are deliberately not listed anywhere: an unlisted global",
        " * stays global and unversioned, which is how they appear in the reference, and is what",
        " * lets a binary linked against this library still run against the real one.",
        " *",
        " * Everything else is hidden by the patterns in the first node's local list.",
        " */",
        "",
    ]

    first = True
    previous = None

    for version in sorted((v for v in groups if v != UNVERSIONED), key=version_key):
        lines.append(f"{version} {{")
        lines.append("    global:")
        lines.extend(f"        {name};" for name in sorted(groups[version]))

        if first:
            lines.append("    local:")
            lines.extend(f"        {pattern};" for pattern in INTERNAL_PATTERNS)
            first = False

        # Each node inherits from the one before it, so the chain reads in release order the
        # way the reference's own map does.
        lines.append(f"}} {previous};" if previous else "};")
        lines.append("")
        previous = version

    out.write_text("\n".join(lines))
    return sum(len(names) for names in groups.values())


def main():
    groups = load()
    build = ROOT / "build"
    build.mkdir(exist_ok=True)

    total = write_version_script(groups, build / "zlib.map")

    print(f"version script: {total} symbols across {len(groups)} nodes -> build/zlib.map")
    return 0


if __name__ == "__main__":
    sys.exit(main())
