#!/usr/bin/env python3
"""Emit a C definition for every exported symbol that is not implemented yet.

The point of this file is that the library always exports the complete API. A client that
calls something unfinished gets a diagnostic and the library's own error value, rather than a
link failure at load time or — far worse — a plausible wrong answer.

Because a name is either in scripts/implemented.txt or defined here, and never both, forgetting
to move a name across when it is implemented is a duplicate-symbol link error rather than
something that silently keeps the stub.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "Sources" / "CZlib" / "include" / "zlib.h"
SYMBOLS = ROOT / "scripts" / "symbols.txt"
IMPLEMENTED = ROOT / "scripts" / "implemented.txt"
OUT = ROOT / "Sources" / "CZlib" / "gen" / "zlib_stubs.c"

# Functions that cannot be generated: a C variadic cannot be defined in Swift at all, and
# neither can one taking a va_list usefully. These stay hand-written C for good, and are not
# stubs — they are where the gz write path will land when it is built.
HAND_WRITTEN = {"gzprintf", "gzvprintf"}

# What each return type's "this did not work" value is, in the convention zlib itself uses.
BY_RETURN = [
    (re.compile(r"\*\s*$"), "NULL"),          # any pointer, including gzFile and char *
    (re.compile(r"^gzFile$"), "NULL"),
    (re.compile(r"^uLong$"), "0"),
    # gzfread/gzfwrite report a short count rather than a negative, so zero is their failure.
    (re.compile(r"^z_size_t$"), "0"),
    (re.compile(r"^int$"), "Z_STREAM_ERROR"),
    (re.compile(r"^unsigned long$|^unsigned$|^unsigned int$"), "0"),
    (re.compile(r"^z_off_t$|^z_off64_t$|^long$"), "-1"),
    (re.compile(r"^void$"), None),
]


def load_exported():
    names = []
    for line in SYMBOLS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("["):
            continue
        names.append(line)
    return names


def load_implemented():
    if not IMPLEMENTED.exists():
        return set()
    return {
        line.strip()
        for line in IMPLEMENTED.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def parse_declarations(text):
    """Every `ZEXTERN <ret> ZEXPORT <name>(<args>);` in the header, newlines and all."""
    pattern = re.compile(
        r"ZEXTERN\s+(?P<ret>[\w\s\*]+?)\s*ZEXPORT\s+(?P<name>\w+)\s*"
        r"\((?P<args>[^;]*?)\)\s*;",
        re.S,
    )
    out = {}
    for match in pattern.finditer(text):
        ret = " ".join(match.group("ret").split())
        args = " ".join(match.group("args").split())
        out[match.group("name")] = (ret, args)
    return out


def split_args(args):
    """Split an argument list on top-level commas, so function-pointer types survive."""
    parts, depth, current = [], 0, ""
    for char in args:
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        if char == "," and depth == 0:
            parts.append(current.strip())
            current = ""
        else:
            current += char
    if current.strip():
        parts.append(current.strip())
    return parts


def name_parameters(args):
    """A definition needs a name for every parameter; the header does not always give one."""
    args = args.strip()
    if args in ("", "void"):
        return "void"

    named = []
    for index, part in enumerate(split_args(args)):
        if part == "...":
            named.append(part)
        elif re.search(r"\w\s*$", part) and not re.search(
            r"\b(void|int|char|long|short|unsigned|const|uLong|uInt|Bytef|z_off_t|"
            r"z_off64_t|z_streamp|gzFile|voidpf|z_crc_t|in_func|out_func|z_size_t|"
            r"gz_headerp|uLongf|Byte|va_list)\s*$",
            part,
        ):
            named.append(part)  # already carries a parameter name
        else:
            named.append(f"{part} p{index}")
    return ", ".join(named)


def failure_value(ret):
    for pattern, value in BY_RETURN:
        if pattern.search(ret):
            return value
    raise SystemExit(f"gen_stubs: no failure value known for return type {ret!r}")


def main():
    declarations = parse_declarations(HEADER.read_text())
    exported = load_exported()
    implemented = load_implemented()

    missing_from_header = [
        name
        for name in exported
        if name not in declarations
        and name not in implemented
        and name not in HAND_WRITTEN
    ]

    lines = [
        "/* Generated by scripts/gen_stubs.py. Do not edit.",
        " *",
        " * One definition per exported symbol that is not implemented yet, so the library",
        " * always resolves its whole API and a gap is reported rather than discovered as a",
        " * missing symbol at load time.",
        " *",
        " * Every symbol is implemented, so this file is empty. It stays in the build because",
        " * the generator is the guard: a name added to symbols.txt without an implementation",
        " * reappears here and fails the covered-count check below.",
        " */",
        "",
        '#include "czlib_shim.h"',
        "",
    ]

    stubbed = []
    pending = [
        name for name in sorted(exported)
        if name not in implemented and name not in HAND_WRITTEN and name in declarations
    ]

    # The reporter is generated with the stubs that call it, and only then: with the surface
    # complete it would be dead weight in the shared object, and a symbol nothing references.
    if pending:
        lines.extend([
            "#include <stdio.h>",
            "",
            "static void swiftzlib_report_unimplemented(const char *name) {",
            '    fprintf(stderr, "swift-zlib: %s is not implemented yet; returning an error.\\n",',
            "            name);",
            "}",
            "",
        ])

    for name in sorted(exported):
        if name in implemented or name in HAND_WRITTEN:
            continue
        if name not in declarations:
            continue

        ret, args = declarations[name]
        value = failure_value(ret)
        params = name_parameters(args)

        # A few exported names are also macros in the header — gzgetc is one — and a
        # definition written under the macro is expanded into nonsense. The reference does the
        # same thing for the same reason.
        lines.append(f"#undef {name}")
        lines.append(f"{ret} {name}({params}) {{")
        lines.append(f'    swiftzlib_report_unimplemented("{name}");')
        lines.append("    return;" if value is None else f"    return {value};")
        lines.append("}")
        lines.append("")
        stubbed.append(name)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))

    print(f"implemented: {len(implemented)}")
    print(f"stubbed:     {len(stubbed)}")
    print(f"hand-written C: {len(HAND_WRITTEN & set(exported))}")
    covered = len(implemented) + len(stubbed) + len(HAND_WRITTEN & set(exported))
    print(f"covered:     {covered} of {len(exported)} exported")

    if missing_from_header:
        print(f"NOT DECLARED IN HEADER: {' '.join(missing_from_header)}", file=sys.stderr)
    if covered != len(exported):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
